changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: "\U0001F680 Features"
      labels:
        - enhancement
        - feature
    - title: "\U0001F41B Bug Fixes"
      labels:
        - bug
        - fix
    - title: "\U0001F4DA Documentation"
      labels:
        - documentation
        - docs
    - title: "\U0001F9F9 Maintenance"
      labels:
        - chore
        - maintenance
        - dependencies
    - title: Other Changes
      labels:
        - "*"
