apiVersion: v1
kind: Service
metadata:
  name: framory
  labels:
    app: framory
spec:
  type: ClusterIP
  selector:
    app: framory
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
